# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-30 11:38
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='related',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='js_services.Service', verbose_name='specific services'),
        ),
    ]
