# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 16:11
from __future__ import unicode_literals

from django.db import migrations, models


def forwards(apps, schema_editor):
    Service = apps.get_model('js_services', 'Service')
    for s in Service.objects.all():
        s.sections.add(s.app_config)

def backward(apps, schema_editor):
    Service = apps.get_model('js_services', 'Service')
    for s in Service.objects.all():
        s.app_config = s.sections.all()[0]
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('js_services', '0007_service_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sections',
            field=models.ManyToManyField(related_name='services', to='js_services.ServicesConfig', verbose_name='Sections'),
        ),
        migrations.RunPython(forwards, backward),
        migrations.RemoveField(
            model_name='service',
            name='app_config',
        ),
    ]
