# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import js_color_picker.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_services', '0009_relatedservicesplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedservicesplugin',
            name='background_color',
            field=js_color_picker.fields.RGBColorField(blank=True, mode='both', null=True, verbose_name='Background Color'),
        ),
        migrations.AddField(
            model_name='relatedservicesplugin',
            name='full_screen',
            field=models.BooleanField(default=False, verbose_name='Show full screen'),
        ),
    ]
