# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('js_services', '0011_auto_20190429_1705'),
    ]

    operations = [
        #migrations.RemoveField(
            #model_name='relatedservicesplugin',
            #name='related_companies',
        #),
        #migrations.RemoveField(
            #model_name='service',
            #name='companies',
        #),
    ]
