# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-17 10:12
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('js_services', '0013_auto_20190709_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='related_articles_placeholder',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_related_articles', slotname='service_related_articles', to='cms.Placeholder'),
        ),
    ]
