# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-24 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import js_color_picker.fields
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_services', '0015_auto_20190807_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesconfig',
            name='allow_post',
            field=models.BooleanField(default=False, verbose_name='Allow POST requests'),
        ),
        migrations.AlterField(
            model_name='relatedservicesplugin',
            name='background_color',
            field=js_color_picker.fields.RGBColorField(blank=True, colors={'#0067A5': 'Dark Blue', '#009fe3': 'Blue', '#0A80C7': 'Medium Blue', '#2D9CDE': 'Light Blue', '#34BCE1': 'Sky', '#545454': 'Dark Grey', '#68C0B5': 'Teal', '#69CCE7': 'Light Sky', '#6d6d6d': 'Grey', '#8FD1E9': 'Very Light Sky', '#96D0C9': 'Light Teal', '#999': 'Light Grey', '#9B8DA5': 'Purple', '#B8AEBF': 'Light Purple', '#BBE9E4': 'Very Light Teal', '#C6BDCB': 'Very Light Purple', '#F2F2F2': 'Very Light Grey', '#F8EB91': 'Yellow', '#FEF4B4': 'Light Yellow', '#FF0000': 'White'}, mode='both', null=True, verbose_name='Background Color'),
        ),
    ]
