# Generated by Django 2.2.9 on 2020-01-28 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import js_color_picker.fields
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_services', '0016_auto_20190924_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='canonical_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Canonical URL'),
        ),
        migrations.AlterField(
            model_name='relatedservicesplugin',
            name='background_color',
            field=js_color_picker.fields.RGBColorField(blank=True, mode='both', null=True, verbose_name='Background Color'),
        ),
        migrations.AlterField(
            model_name='relatedservicesplugin',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='servicesconfigtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='js_services.ServicesConfig'),
        ),
        migrations.AlterField(
            model_name='servicetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='js_services.Service'),
        ),
    ]
