# Generated by Django 2.2.13 on 2020-06-25 23:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import js_color_picker.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_services', '0017_auto_20200128_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='custom_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicesconfig',
            name='custom_fields_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
