# Generated by Django 2.2.13 on 2020-08-14 09:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import js_color_picker.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_services', '0019_auto_20200717_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesconfig',
            name='custom_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relatedservicesplugin',
            name='background_color',
            field=js_color_picker.fields.RGBColorField(blank=True, colors={'#2B3B46': 'dark', '#323B50': 'grey', '#919FA6': 'cool grey', '#CBCBCB': 'medium-grey', '#FBDB4C': 'old maize, do not use!!!', '#FBDD40': 'maize', '#f5f5f5': 'light-grey', '#ffffff': 'white'}, mode='choice', null=True, verbose_name='Background Color'),
        ),
    ]
