# Generated by Django 2.2.10 on 2020-12-09 09:33

from django.db import migrations, models
import js_color_picker.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_services', '0020_auto_20200814_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='layout',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='layout'),
        ),
    ]
