# Generated by Django 2.2.10 on 2021-09-22 18:34

from django.db import migrations, models
import js_color_picker.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_services', '0021_auto_20201209_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetranslation',
            name='layout_trans',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='layout'),
        ),
    ]
