# Generated by Django 2.2.28 on 2024-01-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_services', '0022_auto_20210922_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesconfig',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is featured'),
        ),
    ]
